### ISSUE TITLE
Dynamic set fixed position

### ISSUE THREAD

**Issue by iamsalnikov** [angular-ui/ui-sortable#341] opened 2015-03-04 09:30 UTC
I am rtying to set a fixed item position dynamically. But it work only if the position fixed before init sortable. 

Pen: [http://codepen.io/anon/pen/JoBrzx](http://codepen.io/anon/pen/JoBrzx)

I do a small change into example. In js at line 17 I set timeout, which set to block 1 state `locked` after 1 second. As you can see, we can drag this item.

**Comment by thgreasi** [comment] 2015-03-04 19:11
I expect you might need to do something like `$('[ui-sortable]').sortable('refresh');`, since [jquery-ui might need to learn about the DOM changes](http://api.jqueryui.com/sortable/#method-refresh).

It does not look like it solves the problem though...
Can you reproduce it in plain jquery (& UI) (aka without angular)???

**Comment by thgreasi** [comment] 2015-03-04 19:14
For now, it looks like you will have to rely on `cancel()`.

**Comment by iamsalnikov** [comment] 2015-03-04 19:17
Hm.. But it work ok in reverse way. 

If in initial I have a all locked items, and after 1 second I unlock some of them, then all ok.

Example: [http://codepen.io/anon/pen/GgBdyB](http://codepen.io/anon/pen/GgBdyB)

**Comment by thgreasi** [comment] 2015-03-04 19:33
Really strange things, I have to admit.

But as far I as can tell, this is most likely a jquery-ui related issue, since there is no code in ui-sortable that relates/handles (locked) `items`.

**Comment by iamsalnikov** [comment] 2015-03-05 05:27
Just for test I change my first example, where after 1 second I set `locked` item at index 1. Now I do call `sortable('refresh')` on sortable element. But it not help.

Example: [http://codepen.io/anon/pen/JoBeyg](http://codepen.io/anon/pen/JoBeyg) (line 23. *this way to call `sortable['refresh']` is dirty, I know, but it for test*)

**Comment by thgreasi** [comment] 2015-03-05 05:57
I just [reimplemented your example in plain jQuery (+UI)](http://codepen.io/thgreasi/pen/PwBxej) and as you can see we get the same results. As a result, I'm closing this issue, since it seems it's a jquery-ui issue.

**Closed by thgreasi** 2015-03-05 05:57 UTC
Labels: jquery-ui related, question

**Comment by iamsalnikov** [comment] 2015-03-05 06:18
Ok. Thank you for help. I have [created ticket](http://bugs.jqueryui.com/ticket/11339) on bugs.jqueryui.com.

**Comment by iamsalnikov** [comment] 2015-03-05 15:06
My issue was marked as `duplicated` of this: [http://bugs.jqueryui.com/ticket/5781](http://bugs.jqueryui.com/ticket/5781).

**Comment by thgreasi** [comment] 2015-03-05 15:19
Nice! Kind of...
Anyway, thanks for reporting back :+1:
