### ISSUE TITLE
_connectedSortables is null

### ISSUE THREAD

**Issue by rbedger** [angular-ui/ui-sortable#447] opened 2016-03-30 12:48 UTC
**callbacks.update**
```
var droptargetScope = getElementScope(ui.item.sortable._connectedSortables, droptarget);
ui.item.sortable.droptargetModel = droptargetScope.ngModel;
```

Upon dropping an item into a connected sortable, the above code throws an exception because _connectedSortables is null.  It doesn't seem to end up affecting anything because wrapping it in an if block still works:

```
if (ui.item.sortable._connectedSortables){ 
    var droptargetScope = getElementScope(ui.item.sortable._connectedSortables, droptarget);
    ui.item.sortable.droptargetModel = droptargetScope.ngModel;
}
```

**Comment by thgreasi** [comment] 2016-03-30 13:01
Thanks for reporting!
What version are you using?

Interestingly, I couldn't reproduce using the connected sortables example
from README (http://codepen.io/thgreasi/pen/uFile).
Any change you can share a codepen example of your use case?

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by rbedger** [comment] 2016-03-30 14:15
I'll see if I can get it to replicate outside of our environment

**Comment by thgreasi** [comment] 2016-04-07 14:14
@rbedger Any feedback on this?

**Comment by thgreasi** [comment] 2016-04-17 18:10
Closing this for now.
Please re-open if you find anything more on this.

On Wed, Mar 30, 2016 at 5:15 PM rbedger <notifications@github.com> wrote:

> I'll see if I can get it to replicate outside of our environment
>
> On Wed, Mar 30, 2016 at 9:01 AM Thodoris Greasidis <
> notifications@github.com>
> wrote:
>
> > Thanks for reporting!
> > What version are you using?
> >
> > Interestingly, I couldn't reproduce using the connected sortables example
> > from README (http://codepen.io/thgreasi/pen/uFile).
> > Any change you can share a codepen example of your use case?
> >
> > > --
> > *Thodoris Greasidis*
> > Computer, Networking &
> > Communications Engineer
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/angular-ui/ui-sortable/issues/447#issuecomment-203421398
> >
> >
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-sortable/issues/447#issuecomment-203452140>
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Closed** 2016-04-17 18:10 UTC
