### ISSUE TITLE
Strange behaviour while locking and unlocking a list

### ISSUE THREAD

**Issue by hugomau** [angular-ui/ui-sortable#484] opened 2016-09-02 10:58 UTC
Hi,

I have a variable that is controlling if the list is locked or not. 
It works well before any change in the ordering. 
But as soon as I change the order of an item, and then lock the list again it behaves in an incorrect way.
Now the component is allowing me to reorder the items, which is good but I can still drag the items.

Check it here https://codepen.io/hugomau/pen/WGNrbJ

Any ideia if this a bug or is there something I can do so that if a list is locked the item are not draggable.

Thank you,

Hugo Maurício

**Comment by thgreasi** [comment] 2016-10-10 07:09
Sorry for not replying in a sensible timeframe. I will do my best to investigate in the coming weekend.

**Comment by thgreasi** [comment] 2016-10-19 16:50
Hi there. I'm answering this at last...
This is a [jQuery-UI issue](https://bugs.jqueryui.com/ticket/8532), where [changing the `items` options after the initialization](https://github.com/angular-ui/ui-sortable/issues/268) causes this issue.
This has been [reported before and is related to several issues](https://github.com/angular-ui/ui-sortable/search?utf8=%E2%9C%93&q=lock&type=Issues).

Duplicate of #268, #456, #379.

As noted in the codeped that you forked, you might be able to use the [cancel option](http://api.jqueryui.com/sortable/#option-cancel) for your use case.
```js
// The `cancel` option is preferable,
// in case that you are
// updating the item classes on runtime
// eg: adding/removing the `not-sortable` class
// cancel: ".not-sortable"
// The `items` works in case that
// you are not manipulating the items.
// It also prevents us from placing an item
// above "Item 1" or below "Item 6"
items: "li:not(.not-sortable)"
```
Also, take a look at the alternative approach suggested at #225.

**Closed by thgreasi** 2016-10-19 16:50 UTC
