### ISSUE TITLE
callbacks not executed after drop

### ISSUE THREAD

**Issue by sanathko** [angular-ui/ui-sortable#377] opened 2015-07-15 00:06 UTC
renders the drag and drop contents and can drag and drop the contents as well. But when dragged and dropped, it doesn't hit the update and stop callbacks.
I tried to implement my code in a plunker. (ui sortable wrapped in a directive.)
http://plnkr.co/edit/SK8pr6SbWwM5sYYxT4ON?p=preview
sadly this plunker works as expected, but not my code. (which is close enough with the plunker)
what can be the reasons for not hitting the callback, but renders the draggable content?

**Comment by thgreasi** [comment] 2015-07-16 05:21
The fact that you were not able to reproduce it is really puzzling. Are
getting any logs in the console? You can also check that both directive
options and ng-model have values at the time the directive it's getting
linked.
Such a behavior could be caused by an undefined ng-model. If that's the
case, then give it an initial value of an empty array and update it later,
when you have the actual data.

**Comment by thgreasi** [comment] 2015-07-26 18:00
I'm closing this for now.
Feel free to reopen with more info or example code.

**Closed by thgreasi** 2015-07-26 18:00 UTC
Labels: question
