### ISSUE TITLE
Cannot get it to save first sort, all other sorts save just fine. 

### ISSUE THREAD

**Issue by EmptyPockets** [angular-ui/ui-sortable#358] opened 2015-05-09 23:56 UTC
I'm using ui-sortable with firebase/angularfire to save the data. Here's my setup: 
   
//set options for ui-sortable
    $scope.sortableOptions = {
        stop: function(event, ui) {
            $scope.userList.forEach(function(todo){
              todo.sort = $scope.userList.indexOf(todo);
              $scope.userList.$save(todo);
            });
      },
      axis: 'y'
    }

//the html is like in the example
    <ul ui-sortable="sortableOptions" ng-model="userList">
        <li ng-repeat = "task in userList | orderBy: 'sort'"> 
            {{task.title}}
        </li>
    </ul>

When I try to sort the first time, everything will move back to its original position. If I try to sort again after that everything works great. Any ideas?

**Comment by thgreasi** [comment] 2015-05-10 07:51
Closed as duplicate of #359

**Closed by thgreasi** 2015-05-10 07:51 UTC
Labels: duplicate, question
