### ISSUE TITLE
Sortable auto scroll top/bottom issue

### ISSUE THREAD

**Issue by Atmiya735** [angular-ui/ui-sortable#563] opened 2020-02-26 04:57 UTC
I have 4 section in my page header, desc1, desc2, footer.
I m using draggable to drop section and sortable to make them go to and fro in page.

What i have to do is i have one section in header and i want to make drag and drop that section in footer which is at the bottom of the page. Now when i try to pick the element and move the mouse it does not auto scroll the page as i go down or mgo up. 

Please help me out in this i have check for whole day.
Help is really appreciable 
Thanks, in advance.

**Comment by thgreasi** [comment] 2020-05-29 14:19
Hi, 
This seems to be a duplicate of #430 and also be jquery-ui related and not of the scope of being fixed as part of this lib.
We would love to hear your finding or see a fork of one of our codepen examples demonstrating the issue.
Closing in favor of #430.

**Closed as completed by thgreasi** 2020-05-29 14:19 UTC
