### ISSUE TITLE
Touch events are not currently supported

### ISSUE THREAD

**Issue by mattisdada** [angular-ui/ui-sortable#381] opened 2015-08-20 01:39 UTC
It would be great to see this plugin work with touch events as well as mouse for mobile / tablet use

**Comment by thgreasi** [comment] 2015-08-20 07:18
Duplicate of: #201 #242 #260 #249
All you need to do, is to include [jQuery UI Touch Punch](http://touchpunch.furf.com/) to your pages.

**Closed by thgreasi** 2015-08-20 07:18 UTC

**Comment by thgreasi** [comment] 2015-08-20 07:23
Since no one uses the github issues search for this,   it would be great to just add a mention in README.

PRs welcome.
