### ISSUE TITLE
UI-Sortable is Dependent on DebugInfo Being Enabled

### ISSUE THREAD

**Issue by fishfacemcgee** [angular-ui/ui-sortable#291] opened 2014-11-07 16:22 UTC
I noticed that, after I started using `$compileProvider.debugInfoEnabled(false)` in my my main app module, certain areas using ui-sortable stopped working correctly. [On this line in sortable.js](https://github.com/angular-ui/ui-sortable/blob/master/src/sortable.js#L153), we're using the `scope()` method on an element, which is apparently [only available when debugInfo is active.](https://docs.angularjs.org/guide/production#disabling-debug-data) If we can find a way to get that information without relying on the debug information, that would allow for significant performance improvements by killing debug info outright.

**Comment by smartfaceweb** [comment] 2015-01-04 04:42
I can confirm this issue is still happening in 0.13.1. When debugInfoEnabled = false, the following error is displayed in chrome console:

"Uncaught TypeError: Cannot read property '$eval' of undefined" sortable.js:156.

**Comment by thgreasi** [comment] 2015-01-08 20:36
@fishfacemcgee, @smartfaceweb can you give [my new (badly named) branch](https://github.com/thgreasi/ui-sortable/tree/debugInfoEnabled) some testing?
It should work, it's just the tests that are pending.

**Comment by smartfaceweb** [comment] 2015-01-08 23:56
@thgreasi it works for me, thanks!

Your updated sortable.js looks a lot different to v0.13.1 on angular-ui/ui-sortable with the combineCallbacks function removed and a lot of other tidy up. I've had a look through the git history but can't see where this changed. I am a bit of a noob, can you point me in the right direction.

**Comment by thgreasi** [comment] 2015-01-09 06:34
That's not true, it's [still there](https://github.com/thgreasi/ui-sortable/blob/9f5d328575aeab51ea15d5970fc32cb88463831a/src/sortable.js#L20).
I just opened PR #314 so you can spot the differences easily.

**Comment by smartfaceweb** [comment] 2015-01-11 04:05
Great. Looking forward to the merge so I can update via bower.

**Comment by thgreasi** [comment] 2015-01-15 05:55
#314 seems finished.
If your feedback is OK then this could be merged by tomorrow/the weekend.

**Comment by rainder** [comment] 2015-01-16 16:51
experiencing same issue. waiting for a release. thank you!

**Comment by thgreasi** [comment] 2015-01-16 17:09
Can you provide some feedback on the branch found in #314?

**Closed** 2015-01-20 05:39 UTC

**Comment by thgreasi** [comment] 2015-01-25 20:24
Just created a [repo with a badge](https://github.com/thgreasi/ng-debugInfoDisabled-badges).

![debugInfoEnabled(false) Ready Badge](https://rawgit.com/thgreasi/ng-debugInfoDisabled-badges/master/badge1.svg)

Feel free to use it on your own directive's repo if it is not dependent to DebugInfo being Enabled.
