### ISSUE TITLE
Item in ui-sortable which is not part of the model leads to some weird behaviour

### ISSUE THREAD

**Issue by jo-soft** [angular-ui/ui-sortable#386] opened 2015-09-24 10:55 UTC
Hey Guys,

when inside the ui-sortable one item appears which is not part of the ng-repeat (or the model) two strange thinks happen

* dragging the last one leads to create a new null-object 
* dragging any other one does not change the order

see codepen below for an example

http://codepen.io/anon/pen/avmqje?editors=100

bg,
Johannes

**Comment by thgreasi** [comment] 2015-09-24 11:07
Duplicate of #41.
This is fixed in [v0.14.x branch](https://github.com/angular-ui/ui-sortable/tree/v0.14.x-dev).

**Closed by thgreasi** 2015-09-24 11:07 UTC
